export type AIBadgeType = "generated" | "verified" | "scored" | "flagged" | "detected" | "analyzed";

const badgeLabels: Record<AIBadgeType, string> = {
  generated: "Generated by AI",
  verified: "Verified by AI",
  scored: "Scored by AI",
  flagged: "Flagged by AI",
  detected: "Detected by AI",
  analyzed: "Analyzed by AI",
};

interface AIBadgeProps {
  type?: AIBadgeType;
  label?: string;
  className?: string;
  size?: "sm" | "md" | "lg";
}

export default function AIBadge({
  type = "generated",
  label,
  className = "",
  size = "md",
}: AIBadgeProps) {
  const sizeClass =
    size === "sm" ? "text-xs px-2 py-0.5" : size === "lg" ? "text-sm px-3 py-1" : "text-xs px-2.5 py-0.5";

  return (
    <span className={`badge badge-navy ${sizeClass} ${className}`}>
      {label || badgeLabels[type]}
    </span>
  );
}
